// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generateManifest.js
// Run 'npm run build' to regenerate

import { AssetRecord } from "../types";

export const assets: AssetRecord = {
  frames: [
  {
    "id": "eldritchknight",
    "name": "Eldritchknight",
    "mainCategory": "classes",
    "subCategory": "fighter",
    "thumbnailPath": "eldritchknight_256.png",
    "masterPath": "eldritchknight_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/fighter",
    "maskPath": "eldritchknight_mask.png",
    "tags": [
      "eldritchknight",
      "class",
      "fighter"
    ]
  },
  {
    "id": "hexblade",
    "name": "Hexblade",
    "mainCategory": "classes",
    "subCategory": "warlock",
    "thumbnailPath": "hexblade_256.png",
    "masterPath": "hexblade_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/warlock",
    "maskPath": "hexblade_mask.png",
    "tags": [
      "hexblade",
      "class",
      "warlock"
    ]
  },
  {
    "id": "oldone",
    "name": "Oldone",
    "mainCategory": "classes",
    "subCategory": "warlock",
    "thumbnailPath": "oldone_256.png",
    "masterPath": "oldone_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/warlock",
    "maskPath": "oldone_mask.png",
    "tags": [
      "oldone",
      "class",
      "warlock"
    ]
  },
  {
    "id": "warlock",
    "name": "Warlock",
    "mainCategory": "classes",
    "subCategory": "warlock",
    "thumbnailPath": "warlock_256.png",
    "masterPath": "warlock_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/warlock",
    "maskPath": "warlock_mask.png",
    "tags": [
      "warlock",
      "class",
      "warlock"
    ]
  },
  {
    "id": "astralwarrior",
    "name": "Astralwarrior",
    "mainCategory": "races",
    "subCategory": "astralwarrior",
    "thumbnailPath": "astralwarrior_256.png",
    "masterPath": "astralwarrior_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/races/astralwarrior",
    "maskPath": "astralwarrior_mask.png",
    "tags": [
      "astralwarrior",
      "race",
      "astralwarrior"
    ]
  },
  {
    "id": "kobold",
    "name": "Kobold",
    "mainCategory": "races",
    "subCategory": "kobold",
    "thumbnailPath": "kobold_256.png",
    "masterPath": "kobold_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/races/kobold",
    "maskPath": "kobold_mask.png",
    "tags": [
      "kobold",
      "race",
      "kobold"
    ]
  },
  {
    "id": "starelf",
    "name": "Starelf",
    "mainCategory": "races",
    "subCategory": "starelf",
    "thumbnailPath": "starelf_256.png",
    "masterPath": "starelf_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/races/starelf",
    "maskPath": "starelf_mask.png",
    "tags": [
      "starelf",
      "race",
      "starelf"
    ]
  },
  {
    "id": "nature_acorn",
    "name": "Nature_acorn",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_acorn_256.png",
    "masterPath": "nature_acorn_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_acorn_mask.png",
    "tags": [
      "nature_acorn",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_fey",
    "name": "Nature_fey",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_fey_256.png",
    "masterPath": "nature_fey_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_fey_mask.png",
    "tags": [
      "nature_fey",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_lily",
    "name": "Nature_lily",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_lily_256.png",
    "masterPath": "nature_lily_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_lily_mask.png",
    "tags": [
      "nature_lily",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_moonstone",
    "name": "Nature_moonstone",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_moonstone_256.png",
    "masterPath": "nature_moonstone_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_moonstone_mask.png",
    "tags": [
      "nature_moonstone",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_pink",
    "name": "Nature_pink",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_pink_256.png",
    "masterPath": "nature_pink_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_pink_mask.png",
    "tags": [
      "nature_pink",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_sunflower",
    "name": "Nature_sunflower",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_sunflower_256.png",
    "masterPath": "nature_sunflower_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_sunflower_mask.png",
    "tags": [
      "nature_sunflower",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_thorns",
    "name": "Nature_thorns",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_thorns_256.png",
    "masterPath": "nature_thorns_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_thorns_mask.png",
    "tags": [
      "nature_thorns",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_underdark",
    "name": "Nature_underdark",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_underdark_256.png",
    "masterPath": "nature_underdark_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_underdark_mask.png",
    "tags": [
      "nature_underdark",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "elite_bronze",
    "name": "Elite_bronze",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_bronze_256.png",
    "masterPath": "elite_bronze_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_bronze",
      "utility",
      "elite"
    ]
  },
  {
    "id": "elite_gold",
    "name": "Elite_gold",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_gold_256.png",
    "masterPath": "elite_gold_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_gold",
      "utility",
      "elite"
    ]
  },
  {
    "id": "elite_green",
    "name": "Elite_green",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_green_256.png",
    "masterPath": "elite_green_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_green",
      "utility",
      "elite"
    ]
  },
  {
    "id": "elite_purple",
    "name": "Elite_purple",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_purple_256.png",
    "masterPath": "elite_purple_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_purple",
      "utility",
      "elite"
    ]
  },
  {
    "id": "elite_red",
    "name": "Elite_red",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_red_256.png",
    "masterPath": "elite_red_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_red",
      "utility",
      "elite"
    ]
  },
  {
    "id": "elite_stone",
    "name": "Elite_stone",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_stone_256.png",
    "masterPath": "elite_stone_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_stone",
      "utility",
      "elite"
    ]
  }
],
  backgrounds: [
  {
    "id": "bg_01",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_01.jpg"
  },
  {
    "id": "bg_02",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_02.jpg"
  },
  {
    "id": "bg_03",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_03.jpg"
  },
  {
    "id": "bg_04",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_04.jpg"
  },
  {
    "id": "bg_05",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_05.jpg"
  },
  {
    "id": "bg_06",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_06.jpg"
  },
  {
    "id": "bg_07",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_07.jpg"
  },
  {
    "id": "bg_08",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_08.jpg"
  },
  {
    "id": "bg_09",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_09.jpg"
  },
  {
    "id": "bg_10",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_10.jpg"
  },
  {
    "id": "bg_11",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_11.jpg"
  }
],
  overlays: [
  {
    "id": "fx_01",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/overlays/fx_01.png"
  }
],
  portraits: [
  {
    "id": "portrait_01",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_01.jpg"
  },
  {
    "id": "portrait_02",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_02.jpg"
  },
  {
    "id": "portrait_03",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_03.jpg"
  },
  {
    "id": "portrait_04",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_04.jpg"
  },
  {
    "id": "portrait_05",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_05.jpg"
  },
  {
    "id": "portrait_06",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_06.jpg"
  },
  {
    "id": "portrait_07",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_07.jpg"
  }
],
};
