// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generateManifest.js
// Run 'npm run build' to regenerate

import { AssetRecord } from "../types";

export const assets: AssetRecord = {
  frames: [
  {
    "id": "eldritchknight",
    "name": "Eldritchknight",
    "mainCategory": "classes",
    "subCategory": "fighter",
    "subSubCategory": "eldritchknight",
    "sizes": [
      1024,
      512,
      256
    ],
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/fighter/eldritchknight",
    "tags": [
      "eldritchknight",
      "class",
      "fighter",
      "eldritchknight"
    ]
  },
  {
    "id": "hexblade",
    "name": "Hexblade",
    "mainCategory": "classes",
    "subCategory": "warlock",
    "subSubCategory": "hexblade",
    "sizes": [
      1024,
      512,
      256
    ],
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/warlock/hexblade",
    "tags": [
      "hexblade",
      "class",
      "warlock",
      "hexblade"
    ]
  },
  {
    "id": "oldone",
    "name": "Oldone",
    "mainCategory": "classes",
    "subCategory": "warlock",
    "subSubCategory": "oldone",
    "sizes": [
      1024,
      512,
      256
    ],
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/warlock/oldone",
    "tags": [
      "oldone",
      "class",
      "warlock",
      "oldone"
    ]
  },
  {
    "id": "warlock",
    "name": "Warlock",
    "mainCategory": "classes",
    "subCategory": "warlock",
    "subSubCategory": "warlock",
    "sizes": [
      1024,
      512,
      256
    ],
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/warlock/warlock",
    "tags": [
      "warlock",
      "class",
      "warlock",
      "warlock"
    ]
  },
  {
    "id": "kobold",
    "name": "Kobold",
    "mainCategory": "races",
    "subCategory": "kobold",
    "family": "Dragonkin",
    "sizes": [
      1024,
      512,
      256
    ],
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/races/dragonkin/kobold",
    "tags": [
      "kobold",
      "race",
      "kobold",
      "dragonkin"
    ]
  }
],
};
