// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generateManifest.js
// Run 'npm run build' to regenerate

import { AssetRecord } from "../types";

export const assets: AssetRecord = {
  frames: [
  {
    "id": "eldritchknight",
    "name": "Eldritchknight",
    "mainCategory": "classes",
    "subCategory": "fighter",
    "thumbnailPath": "eldritchknight_256.webp",
    "masterPath": "eldritchknight_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/fighter",
    "maskPath": "eldritchknight_mask.png",
    "tags": [
      "eldritchknight",
      "class",
      "fighter"
    ]
  },
  {
    "id": "hexblade",
    "name": "Hexblade",
    "mainCategory": "classes",
    "subCategory": "warlock",
    "thumbnailPath": "hexblade_256.webp",
    "masterPath": "hexblade_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/warlock",
    "maskPath": "hexblade_mask.png",
    "tags": [
      "hexblade",
      "class",
      "warlock"
    ]
  },
  {
    "id": "oldone",
    "name": "Oldone",
    "mainCategory": "classes",
    "subCategory": "warlock",
    "thumbnailPath": "oldone_256.webp",
    "masterPath": "oldone_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/warlock",
    "maskPath": "oldone_mask.png",
    "tags": [
      "oldone",
      "class",
      "warlock"
    ]
  },
  {
    "id": "warlock",
    "name": "Warlock",
    "mainCategory": "classes",
    "subCategory": "warlock",
    "thumbnailPath": "warlock_256.webp",
    "masterPath": "warlock_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/classes/warlock",
    "maskPath": "warlock_mask.png",
    "tags": [
      "warlock",
      "class",
      "warlock"
    ]
  },
  {
    "id": "astralwarrior",
    "name": "Astralwarrior",
    "mainCategory": "races",
    "subCategory": "astralwarrior",
    "thumbnailPath": "astralwarrior_256.webp",
    "masterPath": "astralwarrior_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/races/astralwarrior",
    "maskPath": "astralwarrior_mask.png",
    "tags": [
      "astralwarrior",
      "race",
      "astralwarrior"
    ]
  },
  {
    "id": "kobold",
    "name": "Kobold",
    "mainCategory": "races",
    "subCategory": "kobold",
    "thumbnailPath": "kobold_256.webp",
    "masterPath": "kobold_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/races/kobold",
    "maskPath": "kobold_mask.png",
    "tags": [
      "kobold",
      "race",
      "kobold"
    ]
  },
  {
    "id": "starelf",
    "name": "Starelf",
    "mainCategory": "races",
    "subCategory": "starelf",
    "thumbnailPath": "starelf_256.webp",
    "masterPath": "starelf_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/races/starelf",
    "maskPath": "starelf_mask.png",
    "tags": [
      "starelf",
      "race",
      "starelf"
    ]
  },
  {
    "id": "nature_acorn",
    "name": "Nature_acorn",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_acorn_256.webp",
    "masterPath": "nature_acorn_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_acorn_mask.png",
    "tags": [
      "nature_acorn",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_fey",
    "name": "Nature_fey",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_fey_256.webp",
    "masterPath": "nature_fey_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_fey_mask.png",
    "tags": [
      "nature_fey",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_lily",
    "name": "Nature_lily",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_lily_256.webp",
    "masterPath": "nature_lily_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_lily_mask.png",
    "tags": [
      "nature_lily",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_moonstone",
    "name": "Nature_moonstone",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_moonstone_256.webp",
    "masterPath": "nature_moonstone_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_moonstone_mask.png",
    "tags": [
      "nature_moonstone",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_pink",
    "name": "Nature_pink",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_pink_256.webp",
    "masterPath": "nature_pink_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_pink_mask.png",
    "tags": [
      "nature_pink",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_sunflower",
    "name": "Nature_sunflower",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_sunflower_256.webp",
    "masterPath": "nature_sunflower_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_sunflower_mask.png",
    "tags": [
      "nature_sunflower",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_thorns",
    "name": "Nature_thorns",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_thorns_256.webp",
    "masterPath": "nature_thorns_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_thorns_mask.png",
    "tags": [
      "nature_thorns",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "nature_underdark",
    "name": "Nature_underdark",
    "mainCategory": "thematic",
    "subCategory": "nature",
    "thumbnailPath": "nature_underdark_256.webp",
    "masterPath": "nature_underdark_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/nature",
    "maskPath": "nature_underdark_mask.png",
    "tags": [
      "nature_underdark",
      "thematic",
      "nature"
    ]
  },
  {
    "id": "berserker",
    "name": "Berserker",
    "mainCategory": "thematic",
    "subCategory": "scifi",
    "thumbnailPath": "berserker_256.webp",
    "masterPath": "berserker_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/scifi",
    "maskPath": "berserker_mask.png",
    "tags": [
      "berserker",
      "thematic",
      "scifi"
    ]
  },
  {
    "id": "brain",
    "name": "Brain",
    "mainCategory": "thematic",
    "subCategory": "scifi",
    "thumbnailPath": "brain_256.webp",
    "masterPath": "brain_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/scifi",
    "maskPath": "brain_mask.png",
    "tags": [
      "brain",
      "thematic",
      "scifi"
    ]
  },
  {
    "id": "detector",
    "name": "Detector",
    "mainCategory": "thematic",
    "subCategory": "scifi",
    "thumbnailPath": "detector_256.webp",
    "masterPath": "detector_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/scifi",
    "maskPath": "detector_mask.png",
    "tags": [
      "detector",
      "thematic",
      "scifi"
    ]
  },
  {
    "id": "overmind",
    "name": "Overmind",
    "mainCategory": "thematic",
    "subCategory": "scifi",
    "thumbnailPath": "overmind_256.webp",
    "masterPath": "overmind_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/scifi",
    "maskPath": "overmind_mask.png",
    "tags": [
      "overmind",
      "thematic",
      "scifi"
    ]
  },
  {
    "id": "plasma",
    "name": "Plasma",
    "mainCategory": "thematic",
    "subCategory": "scifi",
    "thumbnailPath": "plasma_256.webp",
    "masterPath": "plasma_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/scifi",
    "maskPath": "plasma_mask.png",
    "tags": [
      "plasma",
      "thematic",
      "scifi"
    ]
  },
  {
    "id": "psionic",
    "name": "Psionic",
    "mainCategory": "thematic",
    "subCategory": "scifi",
    "thumbnailPath": "psionic_256.webp",
    "masterPath": "psionic_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/scifi",
    "maskPath": "psionic_mask.png",
    "tags": [
      "psionic",
      "thematic",
      "scifi"
    ]
  },
  {
    "id": "soldier",
    "name": "Soldier",
    "mainCategory": "thematic",
    "subCategory": "scifi",
    "thumbnailPath": "soldier_256.webp",
    "masterPath": "soldier_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/scifi",
    "maskPath": "soldier_mask.png",
    "tags": [
      "soldier",
      "thematic",
      "scifi"
    ]
  },
  {
    "id": "winter_dragon",
    "name": "Winter_dragon",
    "mainCategory": "thematic",
    "subCategory": "winter",
    "thumbnailPath": "winter_dragon_256.webp",
    "masterPath": "winter_dragon_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/winter",
    "maskPath": "winter_dragon_mask.png",
    "tags": [
      "winter_dragon",
      "thematic",
      "winter"
    ]
  },
  {
    "id": "winter_elven",
    "name": "Winter_elven",
    "mainCategory": "thematic",
    "subCategory": "winter",
    "thumbnailPath": "winter_elven_256.webp",
    "masterPath": "winter_elven_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/winter",
    "maskPath": "winter_elven_mask.png",
    "tags": [
      "winter_elven",
      "thematic",
      "winter"
    ]
  },
  {
    "id": "winter_knight",
    "name": "Winter_knight",
    "mainCategory": "thematic",
    "subCategory": "winter",
    "thumbnailPath": "winter_knight_256.webp",
    "masterPath": "winter_knight_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/winter",
    "maskPath": "winter_knight_mask.png",
    "tags": [
      "winter_knight",
      "thematic",
      "winter"
    ]
  },
  {
    "id": "winter_matriarch",
    "name": "Winter_matriarch",
    "mainCategory": "thematic",
    "subCategory": "winter",
    "thumbnailPath": "winter_matriarch_256.webp",
    "masterPath": "winter_matriarch_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/winter",
    "maskPath": "winter_matriarch_mask.png",
    "tags": [
      "winter_matriarch",
      "thematic",
      "winter"
    ]
  },
  {
    "id": "winter_nightmare",
    "name": "Winter_nightmare",
    "mainCategory": "thematic",
    "subCategory": "winter",
    "thumbnailPath": "winter_nightmare_256.webp",
    "masterPath": "winter_nightmare_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/winter",
    "maskPath": "winter_nightmare_mask.png",
    "tags": [
      "winter_nightmare",
      "thematic",
      "winter"
    ]
  },
  {
    "id": "winter_primal",
    "name": "Winter_primal",
    "mainCategory": "thematic",
    "subCategory": "winter",
    "thumbnailPath": "winter_primal_256.webp",
    "masterPath": "winter_primal_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/winter",
    "maskPath": "winter_primal_mask.png",
    "tags": [
      "winter_primal",
      "thematic",
      "winter"
    ]
  },
  {
    "id": "winter_scepter",
    "name": "Winter_scepter",
    "mainCategory": "thematic",
    "subCategory": "winter",
    "thumbnailPath": "winter_scepter_256.webp",
    "masterPath": "winter_scepter_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/winter",
    "maskPath": "winter_scepter_mask.png",
    "tags": [
      "winter_scepter",
      "thematic",
      "winter"
    ]
  },
  {
    "id": "winter_shepard",
    "name": "Winter_shepard",
    "mainCategory": "thematic",
    "subCategory": "winter",
    "thumbnailPath": "winter_shepard_256.webp",
    "masterPath": "winter_shepard_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/winter",
    "maskPath": "winter_shepard_mask.png",
    "tags": [
      "winter_shepard",
      "thematic",
      "winter"
    ]
  },
  {
    "id": "winter_tribal",
    "name": "Winter_tribal",
    "mainCategory": "thematic",
    "subCategory": "winter",
    "thumbnailPath": "winter_tribal_256.webp",
    "masterPath": "winter_tribal_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/thematic/winter",
    "maskPath": "winter_tribal_mask.png",
    "tags": [
      "winter_tribal",
      "thematic",
      "winter"
    ]
  },
  {
    "id": "elite_bronze",
    "name": "Elite_bronze",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_bronze_256.webp",
    "masterPath": "elite_bronze_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_bronze",
      "utility",
      "elite"
    ]
  },
  {
    "id": "elite_gold",
    "name": "Elite_gold",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_gold_256.webp",
    "masterPath": "elite_gold_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_gold",
      "utility",
      "elite"
    ]
  },
  {
    "id": "elite_green",
    "name": "Elite_green",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_green_256.webp",
    "masterPath": "elite_green_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_green",
      "utility",
      "elite"
    ]
  },
  {
    "id": "elite_purple",
    "name": "Elite_purple",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_purple_256.webp",
    "masterPath": "elite_purple_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_purple",
      "utility",
      "elite"
    ]
  },
  {
    "id": "elite_red",
    "name": "Elite_red",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_red_256.webp",
    "masterPath": "elite_red_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_red",
      "utility",
      "elite"
    ]
  },
  {
    "id": "elite_stone",
    "name": "Elite_stone",
    "mainCategory": "utility",
    "subCategory": "elite",
    "thumbnailPath": "elite_stone_256.webp",
    "masterPath": "elite_stone_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/elite",
    "maskPath": "elite_mask.png",
    "tags": [
      "elite_stone",
      "utility",
      "elite"
    ]
  },
  {
    "id": "rarity_blue",
    "name": "Rarity_blue",
    "mainCategory": "utility",
    "subCategory": "rarity",
    "thumbnailPath": "rarity_blue_256.webp",
    "masterPath": "rarity_blue_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/rarity",
    "maskPath": "rarity_mask.png",
    "tags": [
      "rarity_blue",
      "utility",
      "rarity"
    ]
  },
  {
    "id": "rarity_green",
    "name": "Rarity_green",
    "mainCategory": "utility",
    "subCategory": "rarity",
    "thumbnailPath": "rarity_green_256.webp",
    "masterPath": "rarity_green_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/rarity",
    "maskPath": "rarity_mask.png",
    "tags": [
      "rarity_green",
      "utility",
      "rarity"
    ]
  },
  {
    "id": "rarity_orange",
    "name": "Rarity_orange",
    "mainCategory": "utility",
    "subCategory": "rarity",
    "thumbnailPath": "rarity_orange_256.webp",
    "masterPath": "rarity_orange_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/rarity",
    "maskPath": "rarity_mask.png",
    "tags": [
      "rarity_orange",
      "utility",
      "rarity"
    ]
  },
  {
    "id": "rarity_purple",
    "name": "Rarity_purple",
    "mainCategory": "utility",
    "subCategory": "rarity",
    "thumbnailPath": "rarity_purple_256.webp",
    "masterPath": "rarity_purple_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/rarity",
    "maskPath": "rarity_mask.png",
    "tags": [
      "rarity_purple",
      "utility",
      "rarity"
    ]
  },
  {
    "id": "rarity_red",
    "name": "Rarity_red",
    "mainCategory": "utility",
    "subCategory": "rarity",
    "thumbnailPath": "rarity_red_256.webp",
    "masterPath": "rarity_red_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/rarity",
    "maskPath": "rarity_mask.png",
    "tags": [
      "rarity_red",
      "utility",
      "rarity"
    ]
  },
  {
    "id": "rarity_white",
    "name": "Rarity_white",
    "mainCategory": "utility",
    "subCategory": "rarity",
    "thumbnailPath": "rarity_white_256.webp",
    "masterPath": "rarity_white_1024.png",
    "basePath": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/frames/utility/rarity",
    "maskPath": "rarity_mask.png",
    "tags": [
      "rarity_white",
      "utility",
      "rarity"
    ]
  }
],
  backgrounds: [
  {
    "id": "bg_01",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_01.jpg"
  },
  {
    "id": "bg_02",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_02.jpg"
  },
  {
    "id": "bg_03",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_03.jpg"
  },
  {
    "id": "bg_04",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_04.jpg"
  },
  {
    "id": "bg_05",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_05.jpg"
  },
  {
    "id": "bg_06",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_06.jpg"
  },
  {
    "id": "bg_07",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_07.jpg"
  },
  {
    "id": "bg_08",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_08.jpg"
  },
  {
    "id": "bg_09",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_09.jpg"
  },
  {
    "id": "bg_10",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_10.jpg"
  },
  {
    "id": "bg_11",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/backgrounds/bg_11.jpg"
  }
],
  overlays: [
  {
    "id": "fx_01",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/overlays/fx_01.png"
  }
],
  portraits: [
  {
    "id": "portrait_01",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_01.jpg"
  },
  {
    "id": "portrait_02",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_02.jpg"
  },
  {
    "id": "portrait_03",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_03.jpg"
  },
  {
    "id": "portrait_04",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_04.jpg"
  },
  {
    "id": "portrait_05",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_05.jpg"
  },
  {
    "id": "portrait_06",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_06.jpg"
  },
  {
    "id": "portrait_07",
    "src": "https://pub-016da068b1e34227b3596a4fcb68d6fd.r2.dev/assets/portraits/portrait_07.jpg"
  }
],
};
